runtime: nodejs20
env: flex

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 3
  cpu_utilization:
    target_utilization: 0.6
  target_concurrent_requests: 100

resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10

readiness_check:
  app_start_timeout_sec: 300
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

liveness_check:
  path: "/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

env_variables:
  NODE_ENV: production
  DATABASE_URL: postgresql://hblab_owner:y1IdMU4EiYfb@ep-falling-flower-a52n1gt7.us-east-2.aws.neon.tech/hblab?sslmode=require&connection_limit=10
